### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by benabraham**
pocita to s textama a obrazkama, co jsou v db na produkci

### CODE REVIEW

**Comment by benabraham** [comment]
sem si to mergnul, trochu se mi nelibi ty volitelny rozdeleni nazvu typu sponzora primo v pythonu

**Comment by starenka** [comment]
To sme dva :)

-----
'aknerats'[::-1]

**Comment by benabraham** [comment]
Na druhou stranu, ten znak od toho je, do toho slova patří. Za mě ok.

**Comment by starenka** [comment]
nejsem si jistej, jestli takovej unicode bordel patri do komentu sloupce v
db, ale kdyz myslis :D

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

2018-04-17 10:12 GMT+02:00 Daniel Srb <notifications@github.com>:

**Comment by benabraham** [comment]
Unicode diskriminace?

**Comment by starenka** [comment]
spis pragmatismus

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Comment by starenka** [comment]
(coz btw v ty migraci de napravit, ze ;) )

---
In Perl you shoot yourself in the foot, but nobody can understand how you
did it. Six months later, neither can you. | print 'aknerats'[::-1]

**Pull request merged**
